name: Publish Docker image

on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - "main"

jobs:
  build_and_push:
    name: Build and possibly Push Docker image to GitHub Packages
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ghcr.io/${{ github.repository }}/manylinux2014_x86_64_opencv3:${{ github.ref_name }}
